# Generated by Django 5.1 on 2024-09-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id_jabatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jabatan', models.CharField(max_length=100)),
                ('gaji_pokok', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id_karyawan', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ttl', models.DateField()),
                ('tgl_bergabung', models.DateField()),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=15)),
                ('id_jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyawan', to='gajianApp.jabatan')),
            ],
        ),
        migrations.CreateModel(
            name='Gaji',
            fields=[
                ('id_gaji', models.AutoField(primary_key=True, serialize=False)),
                ('minggu', models.IntegerField()),
                ('bulan', models.IntegerField()),
                ('total_gaji', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaji', to='gajianApp.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='Potongan',
            fields=[
                ('id_potongan', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_potongan', models.CharField(choices=[('pinjaman', 'Pinjaman'), ('potongan', 'Potongan')], max_length=20)),
                ('jumlah_potongan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_gaji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potongan', to='gajianApp.gaji')),
            ],
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id_presensi', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('tidak', 'Tidak'), ('cuti', 'Cuti'), ('sakit', 'Sakit')], max_length=10)),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='gajianApp.karyawan')),
            ],
        ),
    ]
