# Generated by Django 5.1 on 2024-11-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gajianApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawancasual',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='status',
            field=models.CharField(choices=[('hadir', 'Hadir'), ('tidak hadir', 'Tidak Hadir'), ('cuti', 'Cuti'), ('sakit', 'Sakit')], max_length=20),
        ),
    ]
